
const cityMap = {
  "თბილისი": "Tbilisi",
  "ბათუმი": "Batumi",
  "ქუთაისი": "Kutaisi",
  "რუსთავი": "Rustavi",
  "ზუგდიდი": "Zugdidi",
  "გორი": "Gori",
  "ფოთი": "Poti",
  "თელავი": "Telavi",
  "ახალციხე": "Akhaltsikhe",
  "ხაშური": "Khashuri",
  "ბორჯომი": "Borjomi",
  "მცხეთა": "Mtskheta",
  "ოზურგეთი": "Ozurgeti",
  "სიღნაღი": "Signagi",
  "სენაკი": "Senaki",
  "მარნეული": "Marneuli",
  "ახალქალაქი": "Akhalkalaki",
  "ქობულეთი": "Kobuleti",
  "დუშეთი": "Dusheti",
  "ლაგოდეხი": "Lagodekhi",
  "ნინოწმინდა": "Ninotsminda",
  "ცაგერი": "Tsageri",
  "ამბროლაური": "Ambrolauri",
  "ლანჩხუთი": "Lanchkhuti",
  "ჩხოროწყუ": "Chkhorotsku",
  "საჩხერე": "Sachkhere",
  "ჭიათურა": "Chiatura",
  "წნორი": "Tsnori",
  "ვანი": "Vani",
  "ხონი": "Khoni",
  "დედოფლისწყარო": "Dedoplistskaro",
  "გარდაბანი": "Gardabani",
  "კასპი": "Kaspi",
  "წალკა": "Tsalka",
  "თეთრიწყარო": "Tetritsqaro",
  "საგარეჯო": "Sagarejo",
  "თიანეთი": "Tianeti",
  "ყვარელი": "Kvareli",
  "ონი": "Oni",
  "ბაკურიანი": "Bakuriani",
  "მესტია": "Mestia"
};

export default cityMap;
